### ISSUE TITLE
Local update for the component in dev mode, without server restart

### ISSUE THREAD

**Issue by Liadel** [rambler-digital-solutions/render-react#1]

**Comment by hypersolid** [comment]
@Liadel i've pushed an [update](https://github.com/rambler-digital-solutions/render-react/commit/0f415d3ae40f194cee1634bc277449fc613cc338). Please try to add 

```
Render::React::Config.set_durability(1) if Rails.env.development?
```

to `config/initializers/render_react.rb`

**Comment by Liadel** [comment]
@s74 it works, thanks!
